package com.bobbyprod.common.Products;

public enum ProductStatus {
    IN_STORAGE,
    READY_FOR_PICKUP_AT_WAREHOUSE,
    TRANSFERRING_TO_AGV,
    EN_ROUTE_TO_ASSEMBLY_STATION,
    TRANSFERRING_TO_ASSEMBLY_STATION,
    BEING_ASSEMBLED,
    READY_FOR_PICKUP_AT_ASSEMBLY_STATION,
    EN_ROUTE_TO_WAREHOUSE,
    TRANSFERRING_TO_WAREHOUSE,
}
