@startuml
title AGV Sequence Diagram
actor User
participant Agv
participant AgvService
participant AgvController
participant Mediator
participant RestAPIServer


User -> Agv: processTask(Task)
activate Agv
Agv -> AgvService: handleTask(Task)
activate AgvService
AgvService -> AgvController: loadProgram(programName, state)
activate AgvController
AgvController -> RestAPIServer: HTTP PUT /v1/status (programName, state)
activate RestAPIServer
RestAPIServer -> AgvController: response
deactivate RestAPIServer
AgvController -> AgvService: program loaded
deactivate AgvController
AgvService -> AgvController: changeState(state)
activate AgvController
AgvController -> RestAPIServer: HTTP PUT /v1/status (state)
activate RestAPIServer
RestAPIServer -> AgvController: response
deactivate RestAPIServer
AgvController -> AgvService: state changed
deactivate AgvController

loop until task is completed
    Agv -> AgvService: setState()
    activate AgvService
    AgvService -> AgvController: getAgvController()
    deactivate AgvService
    activate AgvController
    AgvController -> RestAPIServer: getState()
    deactivate AgvController
    activate RestAPIServer
    RestAPIServer -> Agv: response (state)
    deactivate RestAPIServer
end
AgvService -> Agv: handleTask result
deactivate AgvService
Agv -> Mediator: notify(this, task)
activate Mediator
Mediator -> Agv: update task status
deactivate Mediator
activate Agv
Agv -> Agv: update state and battery level
deactivate Agv


@enduml
